### ISSUE TITLE
Unexpected identifier exception - Axios package

### ISSUE THREAD

**Issue by avantida** [rapid7/insightappsec-azure-devops-extension#62]
## Issues and Contributing

After the latest release (1.2.5), there is an exception related with _axios_ package when we run Rapid7 InsightAppSec task in Azure DevOps.

**Exception details:**

2024-02-15T10:57:04.2045708Z ##[error]Unhandled: Unexpected identifier
2024-02-15T10:57:04.2063722Z ##[error]E:\agent-02-work\_tasks\rapid7-insightappsec_69474fb7-a7c2-49ef-a426-f2e0620284c4\1.2.5\node_modules\axios\index.js:1
import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\agent-02-work\_tasks\rapid7-insightappsec_69474fb7-a7c2-49ef-a426-f2e0620284c4\1.2.5\helpers\insightAppSecApi.js:39:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

### Expected Behavior

The ADO task should succeed without failure, as it did using version 1.2.4.

### Actual Behavior

The ADO task fails with **SyntaxError: Unexpected identifier** exception 

### Possible Solution

It might be related with this GH issue: https://github.com/axios/axios/issues/5035

### Steps to Reproduce (for bugs)

1. Make sure version 1.2.5 of the extension is used
2. Run ADO pipeline with Rapid7 InsightAppSec task
3. The task fails with mentioned exception
![image](https://github.com/rapid7/insightappsec-azure-devops-extension/assets/22103001/5c7e491c-f3bb-4509-8ce1-f399f1f84c5e)

### Your Environment
* Extension version: 1.2.5

**Comment by paulinachlewinska** [comment]
yup getting the same

**Comment by andyrooger** [comment]
+1

It fails for me on all our private agents. We don't have any public agent builds to test with.

Does the [task manifest](https://github.com/rapid7/insightappsec-azure-devops-extension/blob/24dfff54ce27e54f36aaf92048cb7acf874100e5/tasks/InsightAppSec/task.json#L150) need updating? The agents bring in node10 and node16, and it's not going to run on node 10 anymore...

**Comment by emcanearney-r7** [comment]
Hi @avantida, @paulinachlewinska , @andyrooger we are able to replicate this our side and are now working on a fix. Will update thread when a new version is available.

**Comment by emcanearney-r7** [comment]
A new version of this plugin has been published with the previously working versions - 1.2.6

**Comment by andyrooger** [comment]
Working again for us. Thanks for the quick turnaround.

**Comment by avantida** [comment]
Works for us too, thanks!
